Kcyganik success msg closes #109
SebChw/Actually-Robust-Training pull request #125
Opened 2023-10-10 11:12 UTC by kordc

closes #109

2023-10-10 12:34 UTC, kordc commented
For now, it looks good, but it doesn't have a message about metric scores. Do we want it?

![image](https://github.com/SebChw/art/assets/72265576/9165fea5-fb90-4b2b-8a4c-71ec9526ebe2)

2023-10-10 12:45 UTC, kordc commented
Now it is better:
![image](https://github.com/SebChw/art/assets/72265576/33591f45-0f8c-4844-b0d6-1cd9aec2bd6a)

2023-10-10 14:17 UTC, SebChw requested changes, later dismissed

2023-10-10 14:17 UTC, SebChw commented on art/experiment/Experiment.py
> +        # print(f"Step {step.name}_{step.get_step_id()} was already completed.")
This can be removed

2023-10-10 14:17 UTC, SebChw commented on art/experiment/Experiment.py
> +                steps_status[step.get_full_step_name()] = ("Skipped", step.get_results())
Use some @dataclasses for this as done in cheks.py. This will be much more readable then just tuple

2023-10-10 14:17 UTC, SebChw commented on art/experiment/Experiment.py
> +        steps_status = {step["step"].get_full_step_name(): ("Not run", None) for step in self.steps}
use defaultdict here

2023-10-10 14:17 UTC, SebChw commented on art/experiment/Experiment.py
> +                continue
We don't want to continue here, it's the philosophy of art. We want to either reraise the exception or just break from the loop. So I'd remove this print and maybe add raised exception to dataclass of `step_status`

2023-10-10 14:17 UTC, SebChw commented on art/experiment/Experiment.py
> +        for step_name, status in steps_status.items():
This is next reason to use dataclasses or just a class. If you implemented __repr__ magic method you could omit this loop

and do: print(status) if you make status an object (dataclass)

2023-10-10 14:17 UTC, SebChw commented on art/experiment/Experiment.py
> +                if 'hash' not in result_name:
This if may grow much bigger. Another argument for putting status in a dataclass

2023-10-10 19:27 UTC, kordc commented
the newest commit closes #108

2023-10-11 19:43 UTC, trebacz626 submitted a review, later dismissed

2023-10-11 19:43 UTC, trebacz626 commented
Approve, but If i remember correctly we wanted to save state into a file, so maybe we can do it here...?

2023-10-12 13:24 UTC, SebChw commented on art/experiment/Experiment.py
> +                continue
@kordc still rest of steps will be run.

2023-10-13 06:36 UTC, kordc commented
> Approve, but If i remember correctly we wanted to save state into a file, so maybe we can do it here...?

done

2023-10-17 12:32 UTC, trebacz626 approved these changes

2023-10-17 15:53 UTC, merged