Kcyganik small changes v03
SebChw/Actually-Robust-Training pull request #185
Opened 2023-11-22 22:45 UTC by kordc

2023-11-22 22:47 UTC, kordc commented
The test will fail until https://github.com/SebChw/ART-Templates/pull/33 is merged

2023-11-23 14:25 UTC, SebChw requested changes
Beside this `setup()` issue LGTM. 

You solved the issue but at cost of running setup dozen of times.

2023-11-23 14:25 UTC, SebChw commented on art/steps.py
> +        if "datamodule" not in trainer_kwargs.keys():
How does this solves the issue of setup? I run EvaluateBaselines step from tutorial and setup was run 6 times for 3 baselines. So you run setup to be able to pass train dataloader. Next lightning runs it too.

2023-11-23 14:31 UTC, SebChw commented on art/steps.py
> +        if "datamodule" not in trainer_kwargs.keys():
Inside here we use datamodule so why you run setup?

2023-11-23 14:51 UTC, SebChw commented on art/steps.py
> +        if "datamodule" not in trainer_kwargs.keys():
Actually this `if` inside `validate` and `test` seems not necessary. If "datamodule" is not in kwargs it means that some dataloader must be. If dataloader is inside trainer kwargs it means that setup must have been run already.

2023-11-23 15:01 UTC, SebChw commented on art/steps.py
> +        self.datamodule.setup(stage=TrainingStage.TRAIN.value)
This doesn't scale well to new steps. My idea would be like this

add `get_trainloader()` Function to the base class Inside which you have try catch statement. If it suceeds it just return train_dataloader if it fails it runs datamodule setup function and then returns train_dataloader

2023-11-25 11:28 UTC, SebChw approved these changes

2023-11-25 18:15 UTC, trebacz626 approved these changes

2023-11-25 19:21 UTC, merged